#!/usr/bin/python3

import amulet
# import requests

seconds = 20000

d = amulet.Deployment(series='trusty')

d.add('nagios')

d.expose('nagios')

try:
    d.setup(timeout=seconds)
    d.sentry.wait()
except amulet.helpers.TimeoutError:
    amulet.raise_status(amulet.SKIP, msg="Environment wasn't stood up in time")
except:
    raise


##
# Set relationship aliases
##
nagios_unit = d.sentry.unit['nagios/0']

d.configure('nagios', {
    'enable_livestatus': True
})

d.sentry.wait()


def test_livestatus_file_exists():
    livestatus_path = nagios_unit.run('config-get livestatus_path')
    try:
        livestatus_file = nagios_unit.file(livestatus_path[0])
    except OSError:
        message = "Can't find livestatus file"
        amulet.raise_status(amulet.FAIL, msg=message)

test_livestatus_file_exists()
