#!/usr/bin/python
from common import units
import os
import subprocess

# We need this to cleanup any hanging units in the tables
if 'JUJU_REMOTE_UNIT' in os.environ:
    this_remote_unit = os.environ['JUJU_REMOTE_UNIT'].replace('/','-')
    valid_units = [x.strip().replace('/','-') for x in subprocess.Popen(['relation-list'],
        stdout=subprocess.PIPE).stdout.readlines()]
    if this_remote_unit not in valid_units:
        valid_units.append(this_remote_unit)
else:
    this_remote_unit = 'testing/0'
    valid_units = ['testing/0']


units.kill_tag(this_remote_unit)
units.cleanup_untagged(valid_units)
os.system('service nagios3 reload')
