#!/usr/bin/python
from common import relations
import os
import subprocess

# We need this to cleanup any hanging relations in the tables
if 'JUJU_RELATION_ID' in os.environ:
    this_relation_id = os.environ['JUJU_RELATION_ID']
    valid_relations = [x.strip() for x in subprocess.Popen(['relation-ids', 'monitors'],
        stdout=subprocess.PIPE).stdout.readlines()]
    if this_relation_id not in valid_relations:
        valid_relations.append(this_relation_id)
else:
    this_relation_id = 'testing'
    valid_relations = ['testing']

relations.kill_tag(this_relation_id)
relations.cleanup_untagged(valid_relations)
os.system('service nagios3 reload')
