#!/usr/bin/python
from common import units, refresh_hostgroups, get_valid_relations
import os
import subprocess

# We need this to cleanup any hanging units in the tables
if 'JUJU_REMOTE_UNIT' in os.environ:
    valid_units = []
    for relation in get_valid_relations():
        valid_units = [x.strip().replace('/','-') for x in subprocess.Popen(['relation-list', '-r', relation],
            stdout=subprocess.PIPE).stdout.readlines()]
    this_remote_unit = os.environ['JUJU_REMOTE_UNIT'].replace('/','-')
    if this_remote_unit not in valid_units:
        valid_units.append(this_remote_unit)
else:
    this_remote_unit = 'testing/0'
    valid_units = ['testing-0']


units.kill_tag(this_remote_unit)
units.cleanup_untagged(valid_units)
refresh_hostgroups()
os.system('service nagios3 reload')
