#!/usr/bin/env python

import string
import sys
import os
import os.path
import yaml
import subprocess
from common import get_ip_and_hostname, get_pynag_host, refresh_hostgroups

from pynag import Model

def main():
        for var in ['JUJU_REMOTE_UNIT', 'JUJU_RELATION_ID']:
            if var not in os.environ:
                print "%s must be set" % (var)
                return 1
        relation_id = os.environ["JUJU_RELATION_ID"]
        remote_unit = os.environ["JUJU_REMOTE_UNIT"]

        service_name, _ = remote_unit.split("/")
        (ip_address, hostname) = get_ip_and_hostname(remote_unit)

        # write a single host
        host = get_pynag_host(hostname, owner_unit=hostname, owner_relation=relation_id)
        host.set_attribute('address', ip_address)
        host.save()

        refresh_hostgroups()

        print "Restarting nagios"
        subprocess.call(["service", "nagios3", "restart"])
        return 0

if __name__ == '__main__':
        sys.exit(main())


