#!/usr/bin/python

import common
hostname=`relation-get private-address`
(_,hostname) = common.get_ip_and_hostname(os.environ['JUJU_REMOTE_UNIT'])
os.unlink('/etc/nagios3/conf.d/%s-config.cfg' % (hostname))
subprocess.call(['service','nagios3','restart'])
