#!/bin/bash

# Arguments:
# $1 = Management Station
# $2 = Community String
# $3 = host_name
# $4 = HostStatID A number that corresponds to the current state of the host: 0=UP, 1=DOWN, 2=UNREACHABLE.
# $5 = HOSTOUTPUT The first line of text output from the last host check (i.e. "Ping OK").
#
/usr/bin/snmptrap -v 2c -c "$2" "$1" "" NAGIOS-NOTIFY-MIB::nHostEvent nHostname s "$3" nHostStateID i "$4" nHostOutput s "$5"

